# Use Ubuntu Xenial
dist: xenial

# Use OpenJDK 11
language: java
jdk: openjdk11

# Cache .m2 directory
cache:
  directories:
    - $HOME/.m2

# Effectively skip the test; just do deployment
script: echo 'Maven POM-packaged build detected. Skipping tests.'
deploy:
  skip_cleanup: true
  on:
    tags: true
  provider: script
  script: travis/deploy.sh
