# Use Ubuntu Xenial
dist: xenial

# Use OpenJDK 11
language: java
jdk: openjdk11

# Cache .m2 directory
cache:
  directories:
    - $HOME/.m2

# Install dependencies; skip everything else
install: ./mvnw -B -V install
  -Dlicense.skip=true
  -Dmaven.test.skip=true
  -Dmaven.source.skip=true
  -Dmaven.javadoc.skip=true
  -Dmaven.install.skip=true

# Effectively skip the test; just do deployment
script: echo 'Maven POM-packaged build detected. Skipping tests.'
deploy:
  skip_cleanup: true
  on:
    tags: true
  provider: script
  script: travis/deploy.sh
